### ISSUE TITLE
streaming hap files missing?

### ISSUE THREAD

**Issue by dpentecost** [keijiro/Vfd9#1]
I may be a little early trying this, but for me the hap files do not show up. All other things from package manager are there (git set up properly, have done it on several machines). The Dkvfx example plays fine with your test file included. Maybe I have to download Take1 and Take8 separately? Thanks!

**Comment by dpentecost** [comment]
Realized these are your recordings, and I was confused by presence of the metadata files but no clips. I did my own DK test recording and it works great, after a bit of mp4 to hap with mov wrapper conversion using https://github.com/Vidvox/hap-in-avfoundation/releases/download/1.4/AVF.Batch.Converter.app.zip - is there another way of doing this conversion?

**Comment by keijiro** [comment]
These video files are copyrighted by another party, so I couldn't include them in this repository. You can just try it by giving your own file as you did.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
